# Generated by Django 5.2.7 on 2025-10-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery_images/')),
                ('alt_text', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HeaderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('hero-image', 'Hero Image')], max_length=20, unique=True)),
                ('image', models.ImageField(upload_to='header_images/')),
            ],
        ),
    ]
