# Generated by Django 5.2.7 on 2025-10-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('about', 'About Section Title'), ('services', 'Services Section Title'), ('process', 'Process Section Title'), ('contact', 'Contact Section Title')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='servicecard',
            name='list_of_services',
            field=models.TextField(help_text='Use new line to separate services'),
        ),
    ]
