# Generated by Django 5.2.7 on 2025-10-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0002_sectiontitle_alter_servicecard_list_of_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectiontitle',
            name='section',
            field=models.CharField(choices=[('about', 'About Section Title'), ('services', 'Services Section Title'), ('process', 'Process Section Title'), ('gallery', 'Gallery Section Title'), ('contact', 'Contact Section Title')], max_length=20, unique=True),
        ),
    ]
