# Generated by Django 5.2.7 on 2025-10-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0003_alter_sectiontitle_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('below-logo', 'Text Below Logo'), ('copyright', 'Copyright Text')], max_length=20, unique=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
